# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'eduskuntatulokset/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@1
  inputs:
    contents: '**/*.jar'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: CopyFiles@1
  inputs:
    contents: '**'
    sourceFolder: 'eduskuntatulokset/src/frontend/build/'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.artifactStagingDirectory)'
    includeRootFolder: true 
    archiveType: 'zip'
    archiveFile: '$(build.artifactStagingDirectory)/$(Build.BuildId).zip' 
    replaceExistingArchive: true


- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'zip'
    pathToPublish: '$(build.artifactStagingDirectory)'
